### ISSUE TITLE
Trackpad axes contain 0 values

### ISSUE THREAD

**Issue by MortimerGoro** [hms-ecosystem/OpenXR-SDK#1]
SDK: hvrsdk-openxr-3.0.0.33

The trackpad (input/trackpad/x and input/trackpad/y) axis values report a value of 0 when using the 3DOF controller.  The "input/trackpad/value" is supposed to represent a touch pressure value but it represents the touch position from left to right (similar to what I would expect from input/trackpad/x)

**Comment by fwei-io** [comment]
VR Team: We know the issue, will compile the source code and try to solve it by the deadline.

**Comment by fwei-io** [comment]
VR Team - delivery date (revised): 11/5/2021

**Comment by Lixming** [comment]
The essence of the problem is that the latest SDK mixes the use of 3-6dof controller profiles. Therefore, to use the paths correctly, please refer to the latest xrdemo, which has been shared with relevant colleagues, and I hope it can help you solve these bugs finally.

**Comment by fwei-io** [comment]
@MortimerGoro here is [HVRSDK_XrDemo](https://drive.google.com/file/d/1lDWOLjVov70fpTQntwRoOmNI3IwcYlVo/view?usp=sharing).

**Comment by MortimerGoro** [comment]
I can get the trackpad/thumbstick values now. I added some demos to (https://github.com/hms-ecosystem/OpenXR-SDK/tree/main/demos/demo_november4)

I found some bugs/things that could be improved, I was able to add some workarounds for them. I remove them when they are fixed in the SDK:
- Tipically trackpad and thumbstick axes are read using XR_TYPE_ACTION_STATE_VECTOR2F, this doesn't work in HVR SDK
- The values should be between -1.0 and 1.0 instead of 0.0 to 1.0
- When using two controllers, the second controller always returns (0.0, 0.0) trackpad values instead of (0.5 0.5 or the current value
- If you don't touch the thumbstick the value is not 0.5, it has some variations around 0.47 or similar. I added some workaround, but ideally the SDK should provide stable value if you are not touching the thumbstick.

**Comment by MortimerGoro** [comment]
I removed Max Priority because I can use the workarounds for the reported issues. This has more priority now (https://github.com/hms-ecosystem/OpenXR-SDK/issues/21)

**Comment by Lixming** [comment]
1. XR_TYPE_ACTION_STATE_VECTOR2F --  /user/hand/left/input/trackpad/value
2. It is 0.0 to 1.0 in our controller.
3. Only one 3dof controller will be supported in the latest SDK.
4. Yes, the error range is 0.05, which is caused by hardware error.

**Comment by fwei-io** [comment]
@MortimerGoro will check XR_TYPE_ACTION_STATE_VECTOR2F -- /user/hand/left/input/trackpad/value and share the findings.

**Comment by MortimerGoro** [comment]
I have modified the code to use XR_TYPE_ACTION_STATE_VECTOR2F and it works well when using a single XrActionSet. When using different XrActionSets each one containing the left or the right actions only one of them works.

**Comment by MortimerGoro** [comment]
I can confirm 3DOf controller trackpad works ok using XR_TYPE_ACTION_STATE_VECTOR2F

**Comment by Lixming** [comment]
@MortimerGoro I have tested the usage of two XrActionSets in my demo app, which could work well. You can refer to the following example code to check your code carefully.

// create actionset
XrActionSetCreateInfo actionSetInfo{XR_TYPE_ACTION_SET_CREATE_INFO};
strcpy(actionSetInfo.actionSetName, "XRDemo");
strcpy(actionSetInfo.localizedActionSetName, "XRDemo");
**actionSetInfo.priority = 0;** // **if you want to use more than one actionset, their priority must be same.**
result = xrCreateActionSet(mInstance, &actionSetInfo, &**m_actionSetL**);
LOGI("xrCreateActionSet:%d", result);

XrActionSetCreateInfo actionSetInfo1{XR_TYPE_ACTION_SET_CREATE_INFO};
strcpy(actionSetInfo1.actionSetName, "XRDemo1");
strcpy(actionSetInfo1.localizedActionSetName, "XRDemo1");
**actionSetInfo1.priority = 0;**
result = xrCreateActionSet(mInstance, &actionSetInfo1, &**m_actionSetR**);
LOGI("xrCreateActionSet:%d", result);

const XrActiveActionSet activeActionSet[]{{m_actionSetL, XR_NULL_PATH}, {m_actionSetR, XR_NULL_PATH}};
XrActionsSyncInfo syncInfo{XR_TYPE_ACTIONS_SYNC_INFO};
syncInfo.countActiveActionSets = 2;
syncInfo.activeActionSets = activeActionSet;
**xrSyncActions**(mSession, &syncInfo); // **update the action value**

**Comment by MortimerGoro** [comment]
Thanks for the info, I have tested and it works. I'm closing the issue.
