### ISSUE TITLE
3D models for the 3DOF and 6DOF controllers

### ISSUE THREAD

**Issue by fwei-io** [hms-ecosystem/OpenXR-SDK#11]
3D models for the 3DOF and 6DOF controllers to display them in the Reality browser. It should also be added to this repo (https://github.com/immersive-web/webxr-input-profiles/tree/main/packages/assets/profiles) to let WebXR developers load real controller models in any WebXR App.

**Comment by fwei-io** [comment]
VR Team - new feature requests.
Delivery dates:
- 3DoF dongle 3D model: 11/19/2021
- 6DoF L/R controllers 3D models: 11/26/2021

**Comment by fwei-io** [comment]
VR Team delivered 6DoF L/R controllers 3D models  - 
https://github.com/hms-ecosystem/OpenXR-SDK/blob/main/lib/VR_Glass_6DoF_Controller_3D_Model.zip

**Comment by MortimerGoro** [comment]
We are waiting for the 3DOf controller model. Blender format would be fine.

**Comment by Lixming** [comment]
@MortimerGoro The model has been shared to relevant colleagues.

**Comment by fwei-io** [comment]
@MortimerGoro please download here, thanks. - https://github.com/hms-ecosystem/OpenXR-SDK/blob/main/lib/VR_Glass_3DoF_Controller_3D_Model.zip

**Comment by fwei-io** [comment]
Closing this issue since both models are received.
