### ISSUE TITLE
VR Glass + firefox  访问 Mozilla hubs 体验问题

### ISSUE THREAD

**Issue by dingsing2021** [hms-ecosystem/OpenXR-SDK#15]
1、使用3dof 手柄进行体验问题，使用的是10月25日的apk包
     1.1 、头部和手柄位置：进入Mozilla hubs 空间后，头部的位置是在地面上的，而手柄的射线是从头部为原点；
      1.2、 按返回键没有起作用，无法从页面退出，只能按home键直接回到launcher；

希望能够在 11月中旬能够解决，11月23日 有一个线上的speech活动需要使用VR Glass + firefox 访问 Mozilla hubs； 从使用便捷度的角度，优先3dof；

**Comment by dingsing2021** [comment]
> > Is it possible to sync up a 3dof version with the head set to a fixed 1.6 m while the handle is 3dof?
> 
> Yes, I added a 3DOF demo here: https://github.com/hms-ecosystem/OpenXR-SDK/tree/main/demos/demos_october29
> 
> I have to separate 3DOF and 6DOF builds for now until 6DOF is able to use the new interaction profile name (#8)

thanks，I have experienced the new version, It has big improvement .

When I went to the Mozilla hubs, when I rotated the helmet on a horizontal plane, the picture was smooth, without the stuttering that I had before.
When using the 3dof handle:
1. The position of the head is normal.
2,However, the position of the handle is not quite right, it is below the ground, so see if this can be solved.
Next, I'll ask my colleagues to test the scenario where multiple people are meeting in the Mozilla Hubs space. Then I'll use the voice microphone to see how it works.

**Comment by dingsing2021** [comment]
> > Is it possible to sync up a 3dof version with the head set to a fixed 1.6 m while the handle is 3dof?
> 
> Yes, I added a 3DOF demo here: https://github.com/hms-ecosystem/OpenXR-SDK/tree/main/demos/demos_october29
> 
> I have to separate 3DOF and 6DOF builds for now until 6DOF is able to use the new interaction profile name (#8)

something added，
 I went to the Mozilla hubs, into a room , use the 6dof controller，when I rotated the helmet on a horizontal plane, The picture still freezes, but not when using the 3dof control handle.

**Comment by fwei-io** [comment]
@dingsing2021 Issue 1, 1.1, 1.2 were resolved by 11/9 demo, please give it a try.

**Comment by dingsing2021** [comment]
> @dingsing2021 Issue 1, 1.1, 1.2 were resolved by 11/9 demo, please give it a try.

yes , i have a try, in 6dof version,  it seems some major issue were resolved.

**Comment by fwei-io** [comment]
@dingsing2021 please let me know if we can close this issue. Thanks.

**Comment by dingsing2021** [comment]
> @dingsing2021 please let me know if we can close this issue. Thanks.

yes，we can close.
