### ISSUE TITLE
Preliminary plan for problem solving

### ISSUE THREAD

**Issue by Lixming** [hms-ecosystem/OpenXR-SDK#17]
1. 【Fixed】delivery date：11/05/2021

- Fixed the bug about trackpad axes contain 0 values
- Share a XR_Demo including the use of 6dof buttom

2. 【Fixed】delivery date：11/19/2021
-Fix the bug of 6dof helmet posture transmission

3. 【Fixed】delivery date：11/26/2021
-Fix the bug of 6dof controller posture transmission

If you have any ideas about the above plan, please feel free to communicate with us.

**Comment by Lixming** [comment]
11/05/2021: As discussed at the meeting, a new plan for bugs fixing is updated.

**Comment by Lixming** [comment]
**11/09/2021:  Both 6dof helmet and 3/6dof controller posture can be obtained.**

Note! Only 6dof app can get 6dof helmet posture. To label the app as 6dof, the method is as followed.
In AndroidManifest.xml, add:
meta-data android:name="com.huawei.vr.application.freeDegree" android:value="6dof" 

@MortimerGoro

**Comment by fwei-io** [comment]
@Lixming please comment on the status of:

- 【Processing】delivery date：11/19/2021 -Fix the bug of 6dof helmet posture transmission
- 【Waiting】delivery date：11/26/2021 - Fix the bug of 6dof controller posture transmission

**Comment by Lixming** [comment]
@fwei-io All FIXED.

**Comment by fwei-io** [comment]
@MortimerGoro please verify and respond if both issues are not fixed.

**Comment by MortimerGoro** [comment]
This has been fixed using the local pose workaround. We can track the xrLocateSpace issue in #5
