### ISSUE TITLE
Positional tracking not working in 6DOF using the latest SDK

### ISSUE THREAD

**Issue by MortimerGoro** [hms-ecosystem/OpenXR-SDK#21]
I've tested the provided demo, and Firefox Reality, with the latest SDKs and the position received for the head (either by using xrLocateSpace or xrLocateViews) doesn't get correct values for HMD head position. 

Positional tracking works in the system app launcher, but not in OpenXR (based on testing the demo and FxR). Do you have the same problem? Is there any service I need to update?

**Comment by Lixming** [comment]
It is a bug,  which is already in the settlement plan.

**Comment by Lixming** [comment]
I guess your application did not add 6DOF label.  To get hemet position, it must be a 6DOF app. You can make your application recognized as a 6dofapp by SDK through the following operations.

In **AndroidManifest.xml**, add:
**<meta-data android:name="com.huawei.vr.application.freeDegree" android:value="6dof"/>**

More details can be referred at the following website. 
[https://developer.huawei.com/consumer/cn/doc/development/graphics-Guides/configuration-manifest-0000001205526407]

**Comment by MortimerGoro** [comment]
Thanks, we didn't have that label in the manifest, I created a new demo with 6DOF fixed (https://github.com/hms-ecosystem/OpenXR-SDK/tree/main/demos/demo_november9)

Now I can also get both the head & controllers on the same reference space, so I based everything on the floor transform to provide correct user height and controller heights
