### ISSUE TITLE
3DoF Controller incorrectly shown when using 6DoF

### ISSUE THREAD

**Issue by lzhangcs** [hms-ecosystem/OpenXR-SDK#29]
![image](https://user-images.githubusercontent.com/63130594/161126630-0d9facf2-2a81-43eb-9e4f-a6938d3a1d18.png)
![image](https://user-images.githubusercontent.com/63130594/161126766-d967247e-a624-4143-a308-c17a71274ad5.png)

**Comment by Lixming** [comment]
Issue #1: please restart your phone.
Issue #2: In 3Dof app, the controller UI model is 3Dof version. It is determined by the developer of the app not by the SDK.

**Comment by lzhangcs** [comment]
Cannot reproduce above issues.
