### ISSUE TITLE
Only the controller with "/user/hand/left" path works

### ISSUE THREAD

**Issue by MortimerGoro** [hms-ecosystem/OpenXR-SDK#3]
SDK: hvrsdk-openxr-3.0.0.33.zip

When using the 6DOF kit dual controllers only the controller with  "/user/hand/left" path seems to be available. And it's associated with the physical right controller instead of the left one

**Comment by MortimerGoro** [comment]
I updated to 3.5.0.67 and now it's able to detect both controllers. However, "/user/hand/left" seems to be still attached to the right controller, so I have to invert controller modes in my local code.

**Comment by fwei-io** [comment]
@VR Team please see https://github.com/hms-ecosystem/OpenXR-SDK/issues/4 last comment

**Comment by fwei-io** [comment]
@MortimerGoro please rebuild, test and share the findings, thanks.

**Comment by MortimerGoro** [comment]
I have seen this comment in the demo version I have:

```
 /* Attention！！！：
 In this demo, index 0 represents the left hand.
 But in the latest released SDK version, 0 represents the right hand. This is a bug that will be solved in the future.
 If you want to get the left hand action data with the latest released SDK, you should use Info.subactionPath = LRPath[1].
 And get the right hand action data with the latest released SDK by using: Info.subactionPath = LRPath[0].
 */
```

So I'll wait until this is fixed in the next SDK version and continue using the workaround for now

**Comment by lzhangcs** [comment]
issue cannot be reproduced.
