### ISSUE TITLE
Issue found on HVR .77 testing version

### ISSUE THREAD

**Issue by lzhangcs** [hms-ecosystem/OpenXR-SDK#33]
For the test version of HVR .77 : https://drive.google.com/file/d/14UpijyQVqiDZ3qbHVBIC5QBkdxtzMLrE/view?usp=sharing

The following issue has be identified by Igalia team:

There is a huge issue happening on my device. The controllers suddenly disconnect themselves without any explanation. Then the VR world starts to move back until you exit the security zone and then, after that, everything gets stalled and nothing more is rendered. There is no way to recover that situation, you have to unplug the glasses. Most of the times I even have to reboot the device because the glasses do not work any longer.

This started to happen with .76 but became more frequent right now to the point that is seriously affecting my capacity to develop on the device.

Also Igalia team wants to see if they can have the following files:
I ask this because among other things Wolvic requires the following files

libxr_loader.so for both arm64-v8 and armeabi-v7 (we can get these from the apk)
The openxr includes: openxr.h, openxr_hw.h, openxr_platform.h ...
The hvrbridge.jar file
Thanks

**Comment by dingsing2021** [comment]
feedback from hvr team: maybe it is a issue Hardware-related, Some early hardware issues. maybe we should updated the firmware of the camera module.

**Comment by svillar** [comment]
Yes, it's definitely hardware related. I switched to another 6dof kit and it's working fine.

You can close the issue.

**Comment by lzhangcs** [comment]
Cannot reproduce.
