### ISSUE TITLE
6DOF controller buttons not tracked

### ISSUE THREAD

**Issue by MortimerGoro** [hms-ecosystem/OpenXR-SDK#4]
SDK: hvrsdk-openxr-3.0.0.33.zip

I'm using a OpenXR input mapping similar to Oculus Quest Touch controller and I can only get this buttons to work:
- Trigger ("/user/hand/left/input/trigger")
- Trackpad ("/user/hand/left/input/trigger") (note that it should be thumbstick ("/user/hand/left/input/thumbstick")

I can't get these other paths to work:
- X ("/user/hand/left/input/x")
- Y  ("/user/hand/left/input/y")
- A  ("/user/hand/left/input/a")
- B  ("/user/hand/left/input/b")
- Thumbrest  ("/user/hand/left/input/thumbrest")
- Squeeze ("/user/hand/left/input/squeeze")

The trackpad/thumbstick axis values are also 0 instead of the correct scroll values.

**Comment by MortimerGoro** [comment]
I updated to 3.5.0.67.

I can only get this buttons to work:

- Trigger ("/user/hand/left/input/trigger")
- Thumbstick ("/user/hand/left/input/thumbstick")  It's using the correct path now instead of Trackpad

I couldn't get these ones to work:

- X ("/user/hand/left/input/x")
- Y ("/user/hand/left/input/y")
- A ("/user/hand/left/input/a")
- B ("/user/hand/left/input/b")
- Thumbrest ("/user/hand/left/input/thumbrest")
- Squeeze ("/user/hand/left/input/squeeze")

The thumbstick axis values are also 0 instead of the correct scroll values.

**Comment by fwei-io** [comment]
@MortimerGoro response:

The mappings are set now here:
https://github.com/MortimerGoro/FirefoxReality/blob/mortimer/hvr_prs/app/src/openxr/cpp/OpenXRInputMappings.h#L192

I tried different combinations of x,y,a,b without luck. You can uncomment the shared lines in local builds.

I added some log message when you click any openxr button (it's in https://github.com/MortimerGoro/FirefoxReality/blob/mortimer/hvr_prs/app/src/openxr/cpp/OpenXRInputSource.cpp#L197)

Alternatively you could send a version of the `HVRSDK_XrDemo` app with the bindings working for the 6DOF controller. The demo is still using the 3DOF buttons so I can't compare with it.

These are the versions I'm using, please let me know if I'm missing any update:

```
VR SDK Service: 3.5.0.67
VR Controller: 9.52.6
SDK: hvrsdk-openxr-3.5.0.67
VR Launcher: 11.1.0.127
```

**Comment by fwei-io** [comment]
VR Team to share a XR_Demo including the use of 6dof buttons - delivery date: 11/5/2021

**Comment by Lixming** [comment]
The latest SDK does not fully support the input paths defined in 6DOF profile, which will be completed in the future. You can refer to the use of the input paths in the latest HVRSDK_XrDemo, which can get all 3-6dof controller key information correctly. And this demo has been shared to relevant colleagues.

**Comment by fwei-io** [comment]
@MortimerGoro here is the [HVRSDK_XrDemo](https://drive.google.com/file/d/1lDWOLjVov70fpTQntwRoOmNI3IwcYlVo/view?usp=sharing).

**Comment by MortimerGoro** [comment]
Thanks, I fixed it using the correct controller values
