### ISSUE TITLE
Controllers: xrLocateSpace does not return local value coordinates when using a localSpace

### ISSUE THREAD

**Issue by MortimerGoro** [hms-ecosystem/OpenXR-SDK#6]
`xrLocateSpace(aimSpace, localSpace, frameState.predictedDisplayTime, &location)`

when using localSpace as a base space to locate controller aim pose values, it seems to return coordinates from the floor instead of returning coordinates relatives to the local origin.

Example:
- Returns the absolute y position from the controller relative to the floor (more than 1 meter), instead of relative to the localSpace origin (could be a small number of centimeters if it's close to the head)

**Comment by fwei-io** [comment]
VR Team - delivery date: 11/19/2021

**Comment by fwei-io** [comment]
Closed and moved to [#5](https://github.com/hms-ecosystem/OpenXR-SDK/issues/5)
